# Generated by Django 5.2.1 on 2025-08-05 06:41

import django.contrib.postgres.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AlterField(
            model_name="concept",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="contentalignment",
            name="content_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AlterField(
            model_name="standard",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Text embedding for similarity search",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="standard",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="standard",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="topiccluster",
            name="common_terms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="topiccluster",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Centroid embedding for cluster",
                null=True,
            ),
        ),
    ]
