# Generated by Django 5.2.1 on 2025-08-06 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standards", "0002_convert_to_vector_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("csv", "CSV File"), ("json", "JSON File")],
                        max_length=10,
                    ),
                ),
                (
                    "clear_existing",
                    models.BooleanField(
                        default=False,
                        help_text="Clear existing standards before import",
                    ),
                ),
                (
                    "generate_embeddings",
                    models.BooleanField(
                        default=False, help_text="Generate embeddings after import"
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=100, help_text="Number of records to process per batch"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating File"),
                            ("processing", "Processing"),
                            ("generating_embeddings", "Generating Embeddings"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("processed_records", models.IntegerField(default=0)),
                ("successful_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                ("progress_percentage", models.FloatField(default=0.0)),
                (
                    "error_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of errors encountered during processing",
                    ),
                ),
                (
                    "processing_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of processing results",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.CharField(
                        help_text="Username of the user who uploaded the file",
                        max_length=150,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Upload Job",
                "verbose_name_plural": "Upload Jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="standards_u_status_e9abc7_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by", "created_at"],
                        name="standards_u_uploade_5ac865_idx",
                    ),
                ],
            },
        ),
    ]
