# Generated by Django 5.2.4 on 2025-08-11 21:27

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_uploadjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='hierarchy',
            field=models.JSONField(blank=True, default=dict, help_text='Parsed hierarchy parts/grade/format'),
        ),
        migrations.AddField(
            model_name='standard',
            name='is_atomic',
            field=models.BooleanField(default=False, help_text='True if already a single learning objective'),
        ),
        migrations.AddField(
            model_name='standard',
            name='normalized_code',
            field=models.CharField(blank=True, db_index=True, help_text='Parsed/normalized representation of the code', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StandardAtom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atom_code', models.CharField(db_index=True, help_text='e.g., CA.SS.3.4.1-A', max_length=50, unique=True)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_generated_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('structural', 'Structural'), ('content', 'Content'), ('gpt', 'GPT'), ('manual', 'Manual')], default='content', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atoms', to='standards.standard')),
            ],
            options={
                'verbose_name': 'Standard Atom',
                'verbose_name_plural': 'Standard Atoms',
                'ordering': ['atom_code'],
                'indexes': [models.Index(fields=['standard'], name='standards_s_standar_2e8f59_idx')],
            },
        ),
        migrations.CreateModel(
            name='StateFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_type', models.CharField(default='generic', max_length=50)),
                ('format_pattern', models.CharField(blank=True, max_length=200)),
                ('example', models.CharField(blank=True, max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='standards.state')),
            ],
            options={
                'verbose_name': 'State Format',
                'verbose_name_plural': 'State Formats',
                'indexes': [models.Index(fields=['state', 'parser_type'], name='standards_s_state_i_05c4f1_idx')],
                'unique_together': {('state', 'parser_type')},
            },
        ),
    ]
