# Generated by Django 5.2.4 on 2025-08-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0006_curriculumdocument_coveragedetail_standardcoverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='title',
            field=models.CharField(blank=True, help_text='Standard title/name (optional - varies by state)', max_length=200, null=True),
        ),
    ]
