# Generated by Django 5.2.4 on 2025-08-13 22:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0007_alter_standard_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_threshold', models.FloatField(default=0.8, help_text='Minimum similarity threshold for creating correlations (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('clear_existing', models.BooleanField(default=False, help_text='Clear existing correlations before generation')),
                ('batch_size', models.IntegerField(default=50, help_text='Number of standards to process per batch')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing Standards'), ('generating', 'Generating Correlations'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('total_standards', models.IntegerField(default=0, help_text='Total standards to process')),
                ('processed_standards', models.IntegerField(default=0, help_text='Standards processed so far')),
                ('correlations_created', models.IntegerField(default=0, help_text='New correlations created')),
                ('correlations_updated', models.IntegerField(default=0, help_text='Existing correlations updated')),
                ('correlations_skipped', models.IntegerField(default=0, help_text='Correlations skipped (duplicates)')),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('avg_processing_time_per_standard', models.FloatField(blank=True, help_text='Average processing time per standard in seconds', null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of errors encountered during processing')),
                ('processing_summary', models.JSONField(blank=True, default=dict, help_text='Summary of processing results')),
                ('statistics', models.JSONField(blank=True, default=dict, help_text='Generation statistics and metrics')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(help_text='Username of the user who started the job', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_filter', models.ManyToManyField(blank=True, help_text='Generate correlations only for these states (empty = all states)', to='standards.state')),
                ('subject_area_filter', models.ForeignKey(blank=True, help_text='Generate correlations only for this subject area', null=True, on_delete=django.db.models.deletion.CASCADE, to='standards.subjectarea')),
            ],
            options={
                'verbose_name': 'Correlation Job',
                'verbose_name_plural': 'Correlation Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='standards_c_status_01bb06_idx'), models.Index(fields=['created_by', 'created_at'], name='standards_c_created_0b8e22_idx'), models.Index(fields=['similarity_threshold'], name='standards_c_similar_61c734_idx')],
            },
        ),
    ]
