# Generated by Django 5.2.4 on 2025-08-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0008_add_correlation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxystandard',
            name='grade_levels',
            field=models.ManyToManyField(blank=True, related_name='proxy_standards', to='standards.gradelevel'),
        ),
        migrations.AddField(
            model_name='proxystandard',
            name='max_grade',
            field=models.IntegerField(blank=True, help_text='Maximum grade level (12 for Grade 12)', null=True),
        ),
        migrations.AddField(
            model_name='proxystandard',
            name='min_grade',
            field=models.IntegerField(blank=True, help_text='Minimum grade level (0 for K)', null=True),
        ),
        migrations.AlterField(
            model_name='proxystandard',
            name='proxy_id',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
