# Generated by Django 5.2.4 on 2025-08-15 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0009_add_grade_levels_to_proxy_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxystandard',
            name='medoid_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medoid_for_proxy', to='standards.standard'),
        ),
        migrations.AddField(
            model_name='proxystandard',
            name='member_standards',
            field=models.ManyToManyField(blank=True, related_name='proxy_memberships', to='standards.standard'),
        ),
        migrations.AddField(
            model_name='proxystandard',
            name='source_type',
            field=models.CharField(choices=[('atoms', 'StandardAtom Clustering'), ('standards', 'Standard Clustering')], default='atoms', max_length=20),
        ),
        migrations.AlterField(
            model_name='proxystandard',
            name='medoid_atom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medoid_for_proxy', to='standards.standardatom'),
        ),
        migrations.AlterField(
            model_name='proxystandard',
            name='member_atoms',
            field=models.ManyToManyField(blank=True, related_name='proxy_memberships', to='standards.standardatom'),
        ),
    ]
