# Generated by Django 5.2.4 on 2025-08-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0010_add_standard_level_clustering'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicBasedProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_id', models.CharField(db_index=True, help_text='Format: TP-Geography-MapSkills-001', max_length=50, unique=True)),
                ('topic', models.CharField(help_text="Main topic (e.g., 'Geography and Spatial Thinking')", max_length=150)),
                ('sub_topic', models.CharField(help_text="Sub-topic (e.g., 'Map Skills and Location')", max_length=150)),
                ('sub_sub_topic', models.CharField(help_text="Sub-sub-topic (e.g., 'Cardinal and Intermediate Directions')", max_length=150)),
                ('title', models.CharField(blank=True, help_text='AI-generated friendly title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Hierarchical description: Topic > Sub-topic > Sub-sub-topic')),
                ('min_grade', models.IntegerField(blank=True, help_text='Minimum grade level from member standards', null=True)),
                ('max_grade', models.IntegerField(blank=True, help_text='Maximum grade level from member standards', null=True)),
                ('outlier_category', models.BooleanField(default=False, help_text="True if this groups standards that didn't fit the main taxonomy")),
                ('standards_count', models.IntegerField(default=0, help_text='Number of member standards')),
                ('states_covered', models.IntegerField(default=0, help_text='Number of unique states represented')),
                ('subject_areas', models.JSONField(blank=True, default=list, help_text='List of subject areas covered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_levels', models.ManyToManyField(blank=True, help_text='All grade levels represented', to='standards.gradelevel')),
                ('member_standards', models.ManyToManyField(blank=True, related_name='topic_proxy_memberships', to='standards.standard')),
            ],
            options={
                'verbose_name': 'Topic-Based Proxy Standard',
                'verbose_name_plural': 'Topic-Based Proxy Standards',
                'ordering': ['topic', 'sub_topic', 'sub_sub_topic', 'proxy_id'],
                'indexes': [models.Index(fields=['topic'], name='standards_t_topic_6b15ec_idx'), models.Index(fields=['topic', 'sub_topic'], name='standards_t_topic_43c224_idx'), models.Index(fields=['topic', 'sub_topic', 'sub_sub_topic'], name='standards_t_topic_ea0632_idx'), models.Index(fields=['outlier_category'], name='standards_t_outlier_07b923_idx'), models.Index(fields=['created_at'], name='standards_t_created_871917_idx')],
            },
        ),
    ]
