# Generated by Django 5.2.1 on 2025-08-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standards", "0013_bulkupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicbasedproxy",
            name="filter_criteria",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete original filtering criteria used during creation",
            ),
        ),
        migrations.AddField(
            model_name="topicbasedproxy",
            name="filter_grade_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Original grade levels used as filter criteria during creation",
            ),
        ),
        migrations.AddField(
            model_name="topicbasedproxy",
            name="filter_subject_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Original subject area filter used during creation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topic_proxies_filtered_for",
                to="standards.subjectarea",
            ),
        ),
    ]
