# Generated by Django 5.2.1 on 2025-08-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standards", "0014_add_topic_proxy_filter_criteria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicbasedproxy",
            name="sub_sub_topic",
            field=models.CharField(
                help_text="Sub-sub-topic (e.g., 'Cardinal and Intermediate Directions') or detailed outlier reasoning",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="topicbasedproxy",
            name="sub_topic",
            field=models.CharField(
                help_text="Sub-topic (e.g., 'Map Skills and Location')", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="topicbasedproxy",
            name="topic",
            field=models.CharField(
                help_text="Main topic (e.g., 'Geography and Spatial Thinking')",
                max_length=500,
            ),
        ),
    ]
